module.exports = {
  reactStrictMode: true,
  images: {
    domains: ['coenraads.gallerycdn.vsassets.io',
      'hollowtree.gallerycdn.vsassets.io',
      'xabikos.gallerycdn.vsassets.io',
      'upload.wikimedia.org',
      'steoates.gallerycdn.vsassets.io',
      'eg2.gallerycdn.vsassets.io',
      'christian-kohler.gallerycdn.vsassets.io',
      'dbaeumer.gallerycdn.vsassets.io',
      'esbenp.gallerycdn.vsassets.io',
      'tabnine.gallerycdn.vsassets.io',
      'eamodio.gallerycdn.vsassets.io',
      'streetsidesoftware.gallerycdn.vsassets.io',
      'msjsdiag.gallerycdn.vsassets.io',
      'formulahendry.gallerycdn.vsassets.io',
      'dsznajder.gallerycdn.vsassets.io',
      'abusaidm.gallerycdn.vsassets.io',
      'johnpapa.gallerycdn.vsassets.io',
      'ritwickdey.gallerycdn.vsassets.io',
      'aaron-bond.gallerycdn.vsassets.io',
      'pkief.gallerycdn.vsassets.io',
      'equinusocio.gallerycdn.vsassets.io',
      'shan.gallerycdn.vsassets.io',
      'wix.gallerycdn.vsassets.io',
      'pranaygp.gallerycdn.vsassets.io',
      'wakatime.gallerycdn.vsassets.io',
      'pnp.gallerycdn.vsassets.io',
      'wmaurer.gallerycdn.vsassets.io'
    ],
  },
}
